export const colorMap: any = {
  white: {
    bgFrom: "from-white",
    bgVia: "via-white",
    bgTo: "to-white",
    text: "text-gray-700",
    linkHover: "hover:text-gray-800",
    accentText: "text-blue-900",
    button: "bg-blue-700",
    buttonTxt: "text-white",
    buttonHover: "hover:bg-blue-800",
    buttonOutline: "border-blue-300 text-blue-700 hover:bg-blue-100",
    cardBgCol: "bg-white-100",
    cardBorderCol: "border-white-300",
    cardTxtCol: "text-white-900",
    secondaryTxtCol: "text-white-600",
    secondaryButtonBg: "bg-white-200",
    secondaryButtonTxt: "text-white-900",
    secondaryButtonHover: "hover:bg-white-300",
    secondaryButtonOutline:
      "border-white-400 text-white-900 hover:bg-white-200",
  },
  gray: {
    bgFrom: "from-gray-50",
    bgVia: "via-white",
    bgTo: "to-gray-100",
    text: "text-gray-700",
    linkHover: "hover:text-gray-900",
    accentText: "text-gray-900",
    button: "bg-gray-700",
    buttonTxt: "text-white",
    buttonHover: "hover:bg-gray-800",
    buttonOutline: "border-gray-300 text-gray-700 hover:bg-gray-100",
    cardBgCol: "bg-gray-100",
    cardBorderCol: "border-gray-300",
    cardTxtCol: "text-gray-900",
    secondaryTxtCol: "text-gray-600",
    secondaryButtonBg: "bg-gray-200",
    secondaryButtonTxt: "text-gray-900",
    secondaryButtonHover: "hover:bg-gray-300",
    secondaryButtonOutline: "border-gray-400 text-gray-900 hover:bg-gray-200",
  },
  zinc: {
    bgFrom: "from-zinc-50",
    bgVia: "via-white",
    bgTo: "to-zinc-100",
    text: "text-zinc-700",
    linkHover: "hover:text-zinc-900",
    accentText: "text-zinc-900",
    button: "bg-zinc-700",
    buttonTxt: "text-white",
    buttonHover: "hover:bg-zinc-800",
    buttonOutline: "border-zinc-300 text-zinc-700 hover:bg-zinc-100",
    cardBgCol: "bg-zinc-100",
    cardBorderCol: "border-zinc-300",
    cardTxtCol: "text-zinc-900",
    secondaryTxtCol: "text-zinc-600",
    secondaryButtonBg: "bg-zinc-200",
    secondaryButtonTxt: "text-zinc-900",
    secondaryButtonHover: "hover:bg-zinc-300",
    secondaryButtonOutline: "border-zinc-400 text-zinc-900 hover:bg-zinc-200",
  },
  slate: {
    bgFrom: "from-slate-50",
    bgVia: "via-white",
    bgTo: "to-slate-100",
    text: "text-slate-700",
    linkHover: "hover:text-slate-900",
    accentText: "text-slate-900",
    button: "bg-slate-700",
    buttonTxt: "text-white",
    buttonHover: "hover:bg-slate-800",
    buttonOutline: "border-slate-300 text-slate-700 hover:bg-slate-100",
    cardBgCol: "bg-slate-100",
    cardBorderCol: "border-slate-300",
    cardTxtCol: "text-slate-900",
    secondaryTxtCol: "text-slate-600",
    secondaryButtonBg: "bg-slate-200",
    secondaryButtonTxt: "text-slate-900",
    secondaryButtonHover: "hover:bg-slate-300",
    secondaryButtonOutline:
      "border-slate-400 text-slate-900 hover:bg-slate-200",
  },
  neutral: {
    bgFrom: "from-neutral-50",
    bgVia: "via-white",
    bgTo: "to-neutral-100",
    text: "text-neutral-700",
    linkHover: "hover:text-neutral-900",
    accentText: "text-neutral-900",
    button: "bg-neutral-700",
    buttonTxt: "text-white",
    buttonHover: "hover:bg-neutral-800",
    buttonOutline: "border-neutral-300 text-neutral-700 hover:bg-neutral-100",
    cardBgCol: "bg-neutral-100",
    cardBorderCol: "border-neutral-300",
    cardTxtCol: "text-neutral-900",
    secondaryTxtCol: "text-neutral-600",
    secondaryButtonBg: "bg-neutral-200",
    secondaryButtonTxt: "text-neutral-900",
    secondaryButtonHover: "hover:bg-neutral-300",
    secondaryButtonOutline:
      "border-neutral-400 text-neutral-900 hover:bg-neutral-200",
  },
  blue: {
    bgFrom: "from-blue-50",
    bgVia: "via-white",
    bgTo: "to-blue-100",
    linkHover: "hover:text-blue-900",
    text: "text-blue-700",
    accentText: "text-blue-900",
    button: "bg-blue-700",
    buttonTxt: "text-white",
    buttonHover: "hover:bg-blue-800",
    buttonOutline: "border-blue-300 text-blue-700 hover:bg-blue-100",
    cardBgCol: "bg-blue-100",
    cardBorderCol: "border-blue-300",
    cardTxtCol: "text-blue-900",
    secondaryTxtCol: "text-blue-600",
    secondaryButtonBg: "bg-blue-200",
    secondaryButtonTxt: "text-blue-900",
    secondaryButtonHover: "hover:bg-blue-300",
    secondaryButtonOutline: "border-blue-400 text-blue-900 hover:bg-blue-200",
  },
  indigo: {
    bgFrom: "from-indigo-50",
    bgVia: "via-white",
    bgTo: "to-indigo-100",
    text: "text-indigo-700",
    linkHover: "hover:text-indigo-900",
    accentText: "text-indigo-900",
    button: "bg-indigo-700",
    buttonTxt: "text-white",
    buttonHover: "hover:bg-indigo-800",
    buttonOutline: "border-indigo-300 text-indigo-700 hover:bg-indigo-100",
    cardBgCol: "bg-indigo-100",
    cardBorderCol: "border-indigo-300",
    cardTxtCol: "text-indigo-900",
    secondaryTxtCol: "text-indigo-600",
    secondaryButtonBg: "bg-indigo-200",
    secondaryButtonTxt: "text-indigo-900",
    secondaryButtonHover: "hover:bg-indigo-300",
    secondaryButtonOutline:
      "border-indigo-400 text-indigo-900 hover:bg-indigo-200",
  },
  violet: {
    bgFrom: "from-violet-50",
    bgVia: "via-white",
    bgTo: "to-violet-100",
    text: "text-violet-700",
    linkHover: "hover:text-violet-900",
    accentText: "text-violet-900",
    button: "bg-violet-700",
    buttonTxt: "text-white",
    buttonHover: "hover:bg-violet-800",
    buttonOutline: "border-violet-300 text-violet-700 hover:bg-violet-100",
    cardBgCol: "bg-violet-100",
    cardBorderCol: "border-violet-300",
    cardTxtCol: "text-violet-900",
    secondaryTxtCol: "text-violet-600",
    secondaryButtonBg: "bg-violet-200",
    secondaryButtonTxt: "text-violet-900",
    secondaryButtonHover: "hover:bg-violet-300",
    secondaryButtonOutline:
      "border-violet-400 text-violet-900 hover:bg-violet-200",
  },
  pink: {
    bgFrom: "from-pink-50",
    bgVia: "via-white",
    bgTo: "to-pink-100",
    text: "text-pink-700",
    linkHover: "hover:text-pink-900",
    accentText: "text-pink-900",
    button: "bg-pink-700",
    buttonTxt: "text-white",
    buttonHover: "hover:bg-pink-800",
    buttonOutline: "border-pink-300 text-pink-700 hover:bg-pink-100",
    cardBgCol: "bg-pink-100",
    cardBorderCol: "border-pink-300",
    cardTxtCol: "text-pink-900",
    secondaryTxtCol: "text-pink-600",
    secondaryButtonBg: "bg-pink-200",
    secondaryButtonTxt: "text-pink-900",
    secondaryButtonHover: "hover:bg-pink-300",
    secondaryButtonOutline: "border-pink-400 text-pink-900 hover:bg-pink-200",
  },
  fuchsia: {
    bgFrom: "from-fuchsia-50",
    bgVia: "via-white",
    bgTo: "to-fuchsia-100",
    text: "text-fuchsia-700",
    linkHover: "hover:text-fuchsia-900",
    accentText: "text-fuchsia-900",
    button: "bg-fuchsia-700",
    buttonTxt: "text-white",
    buttonHover: "hover:bg-fuchsia-800",
    buttonOutline: "border-fuchsia-300 text-fuchsia-700 hover:bg-fuchsia-100",
    cardBgCol: "bg-fuchsia-100",
    cardBorderCol: "border-fuchsia-300",
    cardTxtCol: "text-fuchsia-900",
    secondaryTxtCol: "text-fuchsia-600",
    secondaryButtonBg: "bg-fuchsia-200",
    secondaryButtonTxt: "text-fuchsia-900",
    secondaryButtonHover: "hover:bg-fuchsia-300",
    secondaryButtonOutline:
      "border-fuchsia-400 text-fuchsia-900 hover:bg-fuchsia-200",
  },
  rose: {
    bgFrom: "from-rose-50",
    bgVia: "via-white",
    bgTo: "to-rose-100",
    text: "text-rose-700",
    linkHover: "hover:text-rose-900",
    accentText: "text-rose-900",
    button: "bg-rose-700",
    buttonTxt: "text-white",
    buttonHover: "hover:bg-rose-800",
    buttonOutline: "border-rose-300 text-rose-700 hover:bg-rose-100",
    cardBgCol: "bg-rose-100",
    cardBorderCol: "border-rose-300",
    cardTxtCol: "text-rose-900",
    secondaryTxtCol: "text-rose-600",
    secondaryButtonBg: "bg-rose-200",
    secondaryButtonTxt: "text-rose-900",
    secondaryButtonHover: "hover:bg-rose-300",
    secondaryButtonOutline: "border-rose-400 text-rose-900 hover:bg-rose-200",
  },
  emerald: {
    bgFrom: "from-emerald-50",
    bgVia: "via-white",
    bgTo: "to-emerald-100",
    text: "text-emerald-700",
    linkHover: "hover:text-emerald-900",
    accentText: "text-emerald-900",
    button: "bg-emerald-700",
    buttonTxt: "text-white",
    buttonHover: "hover:bg-emerald-800",
    buttonOutline: "border-emerald-300 text-emerald-700 hover:bg-emerald-100",
    cardBgCol: "bg-emerald-100",
    cardBorderCol: "border-emerald-300",
    cardTxtCol: "text-emerald-900",
    secondaryTxtCol: "text-emerald-600",
    secondaryButtonBg: "bg-emerald-200",
    secondaryButtonTxt: "text-emerald-900",
    secondaryButtonHover: "hover:bg-emerald-300",
    secondaryButtonOutline:
      "border-emerald-400 text-emerald-900 hover:bg-emerald-200",
  },
  green: {
    bgFrom: "from-green-50",
    bgVia: "via-white",
    bgTo: "to-green-100",
    text: "text-green-700",
    linkHover: "hover:text-green-900",
    accentText: "text-green-900",
    button: "bg-green-700",
    buttonTxt: "text-white",
    buttonHover: "hover:bg-green-800",
    buttonOutline: "border-green-300 text-green-700 hover:bg-green-100",
    cardBgCol: "bg-green-100",
    cardBorderCol: "border-green-300",
    cardTxtCol: "text-green-900",
    secondaryTxtCol: "text-green-600",
    secondaryButtonBg: "bg-green-200",
    secondaryButtonTxt: "text-green-900",
    secondaryButtonHover: "hover:bg-green-300",
    secondaryButtonOutline:
      "border-green-400 text-green-900 hover:bg-green-200",
  },
  lime: {
    bgFrom: "from-lime-50",
    bgVia: "via-white",
    bgTo: "to-lime-100",
    text: "text-lime-700",
    linkHover: "hover:text-lime-900",
    accentText: "text-lime-900",
    buttonTxt: "text-white",
    button: "bg-lime-700",
    buttonHover: "hover:bg-lime-800",
    buttonOutline: "border-lime-300 text-lime-700 hover:bg-lime-100",
    cardBgCol: "bg-lime-100",
    cardBorderCol: "border-lime-300",
    cardTxtCol: "text-lime-900",
    secondaryTxtCol: "text-lime-600",
    secondaryButtonBg: "bg-lime-200",
    secondaryButtonTxt: "text-lime-900",
    secondaryButtonHover: "hover:bg-lime-300",
    secondaryButtonOutline: "border-lime-400 text-lime-900 hover:bg-lime-200",
  },
  amber: {
    bgFrom: "from-amber-50",
    bgVia: "via-white",
    bgTo: "to-amber-100",
    text: "text-amber-700",
    linkHover: "hover:text-amber-900",
    accentText: "text-amber-900",
    button: "bg-amber-700",
    buttonTxt: "text-white",
    buttonHover: "hover:bg-amber-800",
    buttonOutline: "border-amber-300 text-amber-700 hover:bg-amber-100",
    cardBgCol: "bg-amber-100",
    cardBorderCol: "border-amber-300",
    cardTxtCol: "text-amber-900",
    secondaryTxtCol: "text-amber-600",
    secondaryButtonBg: "bg-amber-200",
    secondaryButtonTxt: "text-amber-900",
    secondaryButtonHover: "hover:bg-amber-300",
    secondaryButtonOutline:
      "border-amber-400 text-amber-900 hover:bg-amber-200",
  },
  orange: {
    bgFrom: "from-orange-50",
    bgVia: "via-white",
    bgTo: "to-orange-100",
    text: "text-orange-700",
    linkHover: "hover:text-orange-900",
    accentText: "text-orange-900",
    button: "bg-orange-700",
    buttonTxt: "text-white",
    buttonHover: "hover:bg-orange-800",
    buttonOutline: "border-orange-300 text-orange-700 hover:bg-orange-100",
    cardBgCol: "bg-orange-100",
    cardBorderCol: "border-orange-300",
    cardTxtCol: "text-orange-900",
    secondaryTxtCol: "text-orange-600",
    secondaryButtonBg: "bg-orange-200",
    secondaryButtonTxt: "text-orange-900",
    secondaryButtonHover: "hover:bg-orange-300",
    secondaryButtonOutline:
      "border-orange-400 text-orange-900 hover:bg-orange-200",
  },
  red: {
    bgFrom: "from-red-50",
    bgVia: "via-white",
    bgTo: "to-red-100",
    text: "text-red-700",
    linkHover: "hover:text-red-900",
    accentText: "text-red-900",
    button: "bg-red-700",
    buttonTxt: "text-white",
    buttonHover: "hover:bg-red-800",
    buttonOutline: "border-red-300 text-red-700 hover:bg-red-100",
    cardBgCol: "bg-red-100",
    cardBorderCol: "border-red-300",
    cardTxtCol: "text-red-900",
    secondaryTxtCol: "text-red-600",
    secondaryButtonBg: "bg-red-200",
    secondaryButtonTxt: "text-red-900",
    secondaryButtonHover: "hover:bg-red-300",
    secondaryButtonOutline: "border-red-400 text-red-900 hover:bg-red-200",
  },
  yellow: {
    bgFrom: "from-yellow-50",
    bgVia: "via-white",
    bgTo: "to-yellow-100",
    text: "text-yellow-700",
    linkHover: "hover:text-yellow-900",
    accentText: "text-yellow-900",
    button: "bg-yellow-700",
    buttonTxt: "text-white",
    buttonHover: "hover:bg-yellow-800",
    buttonOutline: "border-yellow-300 text-yellow-700 hover:bg-yellow-100",
    cardBgCol: "bg-yellow-100",
    cardBorderCol: "border-yellow-300",
    cardTxtCol: "text-yellow-900",
    secondaryTxtCol: "text-yellow-600",
    secondaryButtonBg: "bg-yellow-200",
    secondaryButtonTxt: "text-yellow-900",
    secondaryButtonHover: "hover:bg-yellow-300",
    secondaryButtonOutline:
      "border-yellow-400 text-yellow-900 hover:bg-yellow-200",
  },
  sky: {
    bgFrom: "from-sky-50",
    bgVia: "via-white",
    bgTo: "to-sky-100",
    text: "text-sky-700",
    linkHover: "hover:text-sky-900",
    accentText: "text-sky-900",
    button: "bg-sky-700",
    buttonTxt: "text-white",
    buttonHover: "hover:bg-sky-800",
    buttonOutline: "border-sky-300 text-sky-700 hover:bg-sky-100",
    cardBgCol: "bg-sky-100",
    cardBorderCol: "border-sky-300",
    cardTxtCol: "text-sky-900",
    secondaryTxtCol: "text-sky-600",
    secondaryButtonBg: "bg-sky-200",
    secondaryButtonTxt: "text-sky-900",
    secondaryButtonHover: "hover:bg-sky-300",
    secondaryButtonOutline: "border-sky-400 text-sky-900 hover:bg-sky-200",
  },
  teal: {
    bgFrom: "from-teal-50",
    bgVia: "via-white",
    bgTo: "to-teal-100",
    text: "text-teal-700",
    linkHover: "hover:text-teal-900",
    accentText: "text-teal-900",
    button: "bg-teal-700",
    buttonTxt: "text-white",
    buttonHover: "hover:bg-teal-800",
    buttonOutline: "border-teal-300 text-teal-700 hover:bg-teal-100",
    cardBgCol: "bg-teal-100",
    cardBorderCol: "border-teal-300",
    cardTxtCol: "text-teal-900",
    secondaryTxtCol: "text-teal-600",
    secondaryButtonBg: "bg-teal-200",
    secondaryButtonTxt: "text-teal-900",
    secondaryButtonHover: "hover:bg-teal-300",
    secondaryButtonOutline: "border-teal-400 text-teal-900 hover:bg-teal-200",
  },
  cyan: {
    bgFrom: "from-cyan-50",
    bgVia: "via-white",
    bgTo: "to-cyan-100",
    text: "text-cyan-700",
    linkHover: "hover:text-cyan-900",
    accentText: "text-cyan-900",
    button: "bg-cyan-700",
    buttonTxt: "text-white",
    buttonHover: "hover:bg-cyan-800",
    buttonOutline: "border-cyan-300 text-cyan-700 hover:bg-cyan-100",
    cardBgCol: "bg-cyan-100",
    cardBorderCol: "border-cyan-300",
    cardTxtCol: "text-cyan-900",
    secondaryTxtCol: "text-cyan-600",
    secondaryButtonBg: "bg-cyan-200",
    secondaryButtonTxt: "text-cyan-900",
    secondaryButtonHover: "hover:bg-cyan-300",
    secondaryButtonOutline: "border-cyan-400 text-cyan-900 hover:bg-cyan-200",
  },
  purple: {
    bgFrom: "from-purple-50",
    bgVia: "via-white",
    bgTo: "to-purple-100",
    text: "text-purple-700",
    linkHover: "hover:text-purple-900",
    accentText: "text-purple-900",
    button: "bg-purple-700",
    buttonTxt: "text-white",
    buttonHover: "hover:bg-purple-800",
    buttonOutline: "border-purple-300 text-purple-700 hover:bg-purple-100",
    cardBgCol: "bg-purple-100",
    cardBorderCol: "border-purple-300",
    cardTxtCol: "text-purple-900",
    secondaryTxtCol: "text-purple-600",
    secondaryButtonBg: "bg-purple-200",
    secondaryButtonTxt: "text-purple-900",
    secondaryButtonHover: "hover:bg-purple-300",
    secondaryButtonOutline:
      "border-purple-400 text-purple-900 hover:bg-purple-200",
  },
  black: {
    bgFrom: "from-gray-900", // Dark gradient start
    bgVia: "via-gray-800", // Gradient middle
    bgTo: "to-black", // Gradient end
    text: "text-white", // Main text
    linkHover: "hover:text-gray-300", // Link hover
    accentText: "text-gray-100", // Accented text
    button: "bg-white", // Button background
    buttonTxt: "text-black", // Button text
    buttonHover: "hover:bg-gray-200", // Button hover
    buttonOutline: "border-gray-600 text-white hover:bg-gray-800", // Outlined button
    cardBgCol: "bg-gray-800", // Card background
    cardBorderCol: "border-gray-700", // Card border
    cardTxtCol: "text-white", // Card text
    secondaryTxtCol: "text-gray-400", // Secondary text
    secondaryButtonBg: "bg-gray-700", // Secondary button background
    secondaryButtonTxt: "text-white", // Secondary button text
    secondaryButtonHover: "hover:bg-gray-600", // Secondary button hover
    secondaryButtonOutline: "border-gray-500 text-white hover:bg-gray-700", // Secondary outlined button
  },
};
